apiVersion: v1
kind: Service
metadata:
  name: spe-frontend-svc
  namespace: default
spec:
  type: NodePort
  selector:
    app: spe-frontend
  ports:
    - port: 4200
      targetPort: 4200
      nodePort: 30170
