---
- name: Deploying with Kubernetes
  hosts: localhost
  tasks:
    - name: install pre-requisites
      pip:
        name:
          - openshift
          - pyyaml
          - kubernetes


    - name: Create spe sqldb credentials
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('file', './kubernetes1/mysqldb-credentials.yml') | from_yml }}"

    - name: Create spe sqldb root credentials
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('file', './kubernetes1/mysqldb-root-credentials.yml') | from_yml }}"

    - name: Create spe sql configmap
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('file', './kubernetes1/mysql-configmap.yml') | from_yml }}"



    - name: Create spe sql deployment
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('file', './kubernetes1/mysql-deployment.yml') | from_yml }}"




    - name: Create Frontend Deployment
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('file', './front-end/kubernetes/deployment.yml') | from_yml }}"
