apiVersion: v1
kind: Service
metadata:
  name: spe-frontend-svc
  namespace: default
spec:
  type: NodePort
  selector:
    app: spe-frontend
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30170
