apiVersion: apps/v1
kind: Deployment
metadata:
  name: spe-app-depl
  namespace: default
spec:
  selector:
    matchLabels:
      app: spe-app
  replicas: 3
  template:
    metadata:
      labels:
        app: spe-app
    spec:
      containers:
        - name: spe-app
          image: spe-app
          ports:
            - containerPort: 9100
          volumeMounts:
            - name: data
              mountPath: /logs
          env:   # Setting Enviornmental Variables
            - name: DB_HOST   # Setting Database host address from configMap
              valueFrom:
                configMapKeyRef:
                  name: db-conf-spe  # name of configMap
                  key: host
            - name: DB_NAME  # Setting Database name from configMap
              valueFrom:
                configMapKeyRef:
                  name: db-conf-spe
                  key: name
            - name: DB_USERNAME  # Setting Database username from Secret
              valueFrom:
                secretKeyRef:
                  name: db-credentials # Secret Name
                  key: username
            - name: DB_PASSWORD # Setting Database password from Secret
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: password
      volumes:
        - name: data
          hostPath:
            path: /home/docker              
        