apiVersion: v1
kind: Service
metadata:
  name: spe-app-svc
  namespace: default
  labels:
    name: spe-app
spec:
  ports:
    - nodePort: 30164
      port: 9100
      targetPort: 9100
      protocol: TCP
  selector:
    app: spe-app
  type: NodePort